All / deny lists for publishing
massdriver-cloud/massdriver-cli pull request #106
Opened 2022-08-21 18:17 UTC by WillBeebe

For apps and bundles

- build -> builds in same directory
- publish -> builds, then copies to a tmp dir, tars the dir and sends to s3

During the copy, all files / dirs at the same level of the `massdriver.yaml` are put through an allowlist. We _only_ copy files or folders in this allowlist.

Once copying one of these allowed folders, we explicitly ignore some files and do some other checks on things like filesize.

2022-08-21 20:07 UTC, WillBeebe commented
I locally ran this against GKE directing output to a `_build` directory so I could inspect it. 

```
ls -al core-services/
total 88
drwxr-xr-x  13 wbeebe  staff   416 Jul 14 11:39 .
drwxr-xr-x  18 wbeebe  staff   576 Aug 19 22:22 ..
drwxr-xr-x   4 wbeebe  staff   128 Jun 11 11:29 .terraform
-rw-r--r--   1 wbeebe  staff  5682 Jun 11 11:29 .terraform.lock.hcl
-rw-r--r--@  1 wbeebe  staff  1285 Jul  8 12:51 _artifacts.tf
-rw-r--r--@  1 wbeebe  staff   157 Aug 21 13:00 _connections_variables.tf.json
-rw-r--r--@  1 wbeebe  staff    89 Aug 21 13:00 _md_variables.tf.json
-rw-r--r--@  1 wbeebe  staff   359 Aug 21 13:00 _params_variables.tf.json
-rw-r--r--@  1 wbeebe  staff  1491 Jul  8 12:51 _providers.tf
-rw-r--r--   1 wbeebe  staff  3181 Jun 17 17:39 core_services.tf
-rw-r--r--   1 wbeebe  staff   400 Jun  9 21:25 locals.tf
-rw-r--r--   1 wbeebe  staff   369 Jun 17 17:39 observability.tf
-rw-r--r--   1 wbeebe  staff   943 Jun  9 21:25 service_account.tf

ls _build/
core-services           massdriver.yaml         schema-connections.json schema-ui.json
custom-resources        schema-artifacts.json   schema-params.json      src

ls _build/core-services/
_artifacts.tf      _providers.tf      core_services.tf   locals.tf          observability.tf   service_account.tf
```

2022-08-22 00:38 UTC, coryodaniel commented on pkg/common/constants.go
> +	"src",
Do we look for `steps` to see if there are any other directories to load?

2022-08-22 00:42 UTC, WillBeebe commented on pkg/common/constants.go
> +	"src",
We sure do. If steps are not nil we add all steps to the allow list and dedupe

2022-08-22 01:00 UTC, coryodaniel requested changes
Im not sure whats up, but this does publish (and `mass ___ build` looks right), but provisioning fails due to missing variables. Depending on the run connections are missing or md_metadata is missing. I ran the provisioner for other bundles that weren't published w/ this branch and they work.

Maybe we should make a local `_build` directory in the repo where `massdriver.yaml` is that isn't a tmp dir (is gitignored in our .gitignore template) so we can see whats in this directory.

2022-08-22 01:08 UTC, coryodaniel requested changes
I can't add a suggestion because the files aren't editable, Im not sure how this worked before, but the following files _need_ to be in the bundle:

```
	// // Auto generated terraform variable files
	// "_connections_variables.tf.json",
	// "_params_variables.tf.json",
	// "_md_variables.tf.json",

2022-08-22 01:09 UTC, coryodaniel commented
I commented those out locally and the build worked.

2022-08-22 01:27 UTC, WillBeebe commented
> I commented those out locally and the ~build~ **PUBLISH** worked.

I lost my way a bit in the allow / ignore and order of operations but 🤦 duh we need those! I commented them out w/ a danger note for future devs, and added a test.

2022-08-22 04:30 UTC, coryodaniel commented
I’d remove them. They should never be I commented.

Cory ODaniel
Mobile: 310.606.0257
***@***.***
medium: @coryodaniel ***@***.***>
twitter: @coryodaniel <https://twitter.com/coryodaniel>

On Sun, Aug 21 2022 at 6:27 PM, Will Beebe ***@***.***>
wrote:

> I commented those out locally and the build *PUBLISH* worked.
>
> I lost my way a bit in the allow / ignore and order of operations but [image:
> 🤦] duh we need those! I commented them out w/ a danger note for future
> devs, and added a test.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/massdriver-cloud/massdriver-cli/pull/106#issuecomment-1221683577>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAC2Q5EFR5QP2VSYEG2RBTV2LJPNANCNFSM57FK2W3A>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-08-22 04:55 UTC, coryodaniel commented on pkg/common/constants.go
> +	"src",
🚀

2022-08-22 17:07 UTC, jaketf requested changes

2022-08-22 17:07 UTC, jaketf commented on pkg/common/copy.go
> +// If a step has a folder like .terraform, path.Walk will still traverse it
hmm, I think it will be less code / more maintainable if we use the canonical Walk pattern. 
You can avoid walking a dir by your `WalkFunc` returning the special error `filepath.SkipDir`. 

from path/filepath godocs [here](https://pkg.go.dev/path/filepath#pkg-variables:~:text=SkipDir%20is%20used%20as%20a%20return%20value%20from%20WalkFuncs%20to%20indicate%20that%20the%20directory%20named%20in%20the%20call%20is%20to%20be%20skipped.%20It%20is%20not%20returned%20as%20an%20error%20by%20any%20function.):

> SkipDir is used as a return value from `WalkFunc`s to indicate that the directory named in the call is to be skipped. It is not returned as an error by any function.

you can see how it is used in the [filepath.Walk example](https://pkg.go.dev/path/filepath#example-Walk)

2022-08-22 17:08 UTC, WillBeebe commented
Ticket [here](https://github.com/massdriver-cloud/massdriver/issues/1297) and I updated the file in the PR. 💪

2022-08-22 17:09 UTC, WillBeebe commented on pkg/common/copy.go
> +// If a step has a folder like .terraform, path.Walk will still traverse it
That would have saved some time. :) Do you think this is blocking or can we come back to it?

2022-08-22 17:20 UTC, WillBeebe commented on pkg/common/copy.go
> +// If a step has a folder like .terraform, path.Walk will still traverse it
Alright, I'll make these changes

2022-08-22 17:22 UTC, chrisghill reviewed
Looks good. Some minor feedback and naming suggestions.

2022-08-22 17:22 UTC, chrisghill commented on pkg/bundle/testdata/zipdir/schema-ui.json
> +}
Leaving the comment here, cuz I can't comment on the empty file.

I just want to make sure the file below (`.terraform/stuff.tf`) is there to test **ignore** functionality. We def don't want `.terraform` in the bundle package.

2022-08-22 17:22 UTC, chrisghill commented on pkg/common/constants.go
> +	"_connections.auto.tfvars.json",
We can probably just do `tfvars.json`.  If somebody accidentally misspells `_conections.auto.tfvars.json` we don't want to let that through.

Edit: should do `.tfvars` and `.tfvars.json` in case some users set variables without using json.

2022-08-22 17:22 UTC, chrisghill commented on pkg/common/constants.go
> +	"src",
Are we having folders in the `FileAllows` list? This becomes unclear exactly what this list is for.

At first I assumed it was looking for filenames that matched the string. What does it do w/ directories?

2022-08-22 17:22 UTC, chrisghill commented on pkg/common/copy.go
> +		return ioutil.WriteFile(dest, data, AllRWX)
It would be great to retain `chmod` settings on the copy over if that's possible, instead of making everything `777`. If we can't, honestly we might want to just do `UserRW`. The provisioning runs as the `massdriver` user, and when it unzips it should inherit the "user" permissions. Nothing else should need to read, write, or execute the file.

2022-08-22 17:22 UTC, chrisghill commented on pkg/common/copy.go
> +	errMkdir := os.Mkdir(dest, AllRX|UserRW)
Same with directories, but I'm less concerned about dir permissions.

2022-08-22 17:22 UTC, chrisghill commented on pkg/common/copy.go
> +		log.Debug().Msgf("File: %s is larger than limit of %vMB.", fileName, MaxFileSizeMB)
Should make this an `Error` or at least a `Warning`. This will effectively be a *silent* failure if its hidden in debug logs.

2022-08-22 17:22 UTC, chrisghill commented on pkg/common/copy_test.go
> +			if gotMD5 != wantMD5 {
I wish there was a better way to check folder equality than these fragile MD5 hashes, bit it works for now.

2022-08-22 17:28 UTC, WillBeebe commented on pkg/bundle/testdata/zipdir/schema-ui.json
> +}
Yes I explicitly named it `.terraform` to make sure it's excluding in the Package phase.

2022-08-22 19:04 UTC, coryodaniel commented on pkg/common/constants.go
> +	"_connections.auto.tfvars.json",
^ yes.

2022-08-22 19:05 UTC, coryodaniel commented on pkg/common/copy_test.go
> +			if gotMD5 != wantMD5 {
There was a walk and diff I added for app templates... https://github.com/massdriver-cloud/massdriver-cli/blob/971d2723caefcff297b2a6aeb673852acd4dc217/pkg/template/render_test.go#L83

2022-08-22 20:20 UTC, WillBeebe commented on pkg/common/constants.go
> +	"_connections.auto.tfvars.json",
Okay, any filename that contains `.tfvars` is ignored by one of the earlier file ignores. I yanked these explicit ones.

2022-08-22 20:21 UTC, WillBeebe commented on pkg/common/constants.go
> +	"src",
It follows the same logic. If the string we want to copy (file or folder) matches any of these, we include it.

2022-08-22 20:21 UTC, WillBeebe commented on pkg/common/copy.go
> +		return ioutil.WriteFile(dest, data, AllRWX)
Great point, thank you

2022-08-22 20:24 UTC, WillBeebe commented on pkg/bundle/package.go
> +	return tarFolder(buildDir+"/"+common.MassdriverYamlFilename, buf)
Good point, this was legacy logic as things were being consolidated. I can drop the filename now and just pass the dir.

2022-08-22 21:58 UTC, jaketf approved these changes
some small suggestions otherwise looks good! thanks for making the WalkFunc change!

2022-08-22 21:58 UTC, jaketf commented on pkg/bundle/package.go
> +	buildDir, err := os.MkdirTemp("", "bundle-build")
should this temp dir include the bundle name (or at least a * to add some randomness) to avoid temp dir name collision? kind of a weird scenario but if you were packaging multiple bundles with different names concurrently (e.g. in CI) it'd be a frustrating if this temp dir name made that not possible.

2022-08-22 21:58 UTC, jaketf commented on pkg/bundle/package.go
> +	allAllows := []string{}
non-blocking educational nit: could be more efficient we know the  length of this slice apriori so could pre-allocate.
though this might be slightly less readable.
```suggestion
	allAllows := make([]string, len(common.FileAllows) + len(b.Steps))
	copy(allAllows, common.FileAllows)
	if b.Steps != nil {
	  for i, step := range b.Steps {
	    allAllows[len(common.FileAllows)+i] = step.Path
	  }
	}
```

2022-08-22 21:58 UTC, jaketf commented on pkg/bundle/package_test.go
> +			// testDir := "_build"
remove commented out code which I assume is a debugging artifact

2022-08-22 21:58 UTC, jaketf commented on pkg/common/utils.go
> +		if _, value := keys[entry]; !value {
this "value" name is low-key really misleading because it's actually a bool that indicates if the key was found _not_ the value for that key... (though the way you're using this data structure those will _happen_ to be the same value if we ever introduced a bug in this code it'd be a real head scratcher)
In most go code I've seen the common idiom when using the dual assignment from a map key lookup is to use the name `ok` in this scenario.
```suggestion
		if _, ok := keys[entry]; !ok {
```

that being said I don't event think that is necessary here as map[string]bool will return the zero value  false if the key is not found so the following would be a more succinct way to express what's going on here. 
```suggestion
		if keys[entry] {
```
finally I think keys should be called something like `seen` to indicate these are the unique values we've already seen.

2022-08-22 21:58 UTC, jaketf commented on pkg/common/utils.go
> +const tenTwentyFour = 1024
lol was this to make the linter happy?

I typically see these magic numbers named something more descriptive.
Also there's no reason for the extra memory allocation / math operation of calcuating kilobytes if you only care about megabytes.
```suggestion
const bytesInMB = 1024 * 1024
```

2022-08-22 22:03 UTC, coryodaniel commented
PS, ive packaged w/ this branch like 10 times today and have had no issues.

2022-08-22 22:17 UTC, WillBeebe commented on pkg/common/utils.go
> +		if _, value := keys[entry]; !value {
I didn't know I could do that for a function that returns two values! V cool. I rewrote and renamed this locally 👍

2022-08-22 22:18 UTC, WillBeebe commented on pkg/common/utils.go
> +const tenTwentyFour = 1024
Lol yes. Thanks for the code suggestion.

2022-08-22 22:21 UTC, WillBeebe commented on pkg/bundle/package.go
> +	allAllows := []string{}
Since the number of elements are so low I think I'll favor the readability here but you make a great point.

2022-08-22 22:24 UTC, WillBeebe commented on pkg/bundle/package.go
> +	buildDir, err := os.MkdirTemp("", "bundle-build")
I'm pretty sure it already does add a random suffix.

https://pkg.go.dev/os#MkdirTemp

If we wanted it at a different position in the string we could do `bundle-*-build` but I'm pretty sure as-is it will be `bundle-build128381910`. LMK what you think.

2022-08-22 22:24 UTC, WillBeebe commented on pkg/bundle/package.go
> +	buildDir, err := os.MkdirTemp("", "bundle-build")
Also, this might just be a readability thing. I'll use `bundle-build-*` so it's more clear. 👍

2022-08-23 23:28 UTC, coryodaniel approved these changes

2022-08-23 23:48 UTC, merged