[WIP] App is_a bundle
massdriver-cloud/massdriver-cli pull request #87
Opened 2022-08-11 03:29 UTC by WillBeebe

- apps _are_ bundles
- apps have connections, they are JSON schema 
- no more dependencies
- updated tests

2022-08-11 04:30 UTC, WillBeebe commented on pkg/bundle/templates/terraform/massdriver.yaml
>  connections:
support no-connections

2022-08-11 10:51 UTC, coryodaniel commented
Example YAML, I approximated the names of things.

```yaml
schema: draft-07
name: express-app-demo
description: An example express application using Massdriver
ref: github.com/massdrover-cloud/express-app-demo
access: private
type: application

params:
  properties:
    name:
      type: string
    log_level:
      type: string
      enum: ["warn", "error", "info"]
    namespace:
      type: string
      default: default
    replication:
      type: string
      enum:
        - async
        - sync

connections:
  required: "*"
  properties:
    kubernetes_cluster:
      $ref: massdriver/k8s
    mongo:
      $ref: massdriver/mongo-authentication
    sqs:
      $ref: massdriver/aws-sqs-pubsub-subscription
    s3:
      $ref: massdriver/aws-s3-application-assets-bucket

app:
  envs:
    MONGO_USERNAME: connections.mongo.path.to.username
    LOG_LEVEL: params.log_level
    STRIPE_KEY: secrets.ecomm_site_stripe_key # these would be set in MD at the target level; TBD in future

  policies:
    - connections.sqs.path.to.read.policy
    - connections.s3.path.to.write.policy

```

2022-08-11 22:21 UTC, coryodaniel commented on pkg/bundle/templates/terraform/massdriver.yaml
>  connections:
We always need a connection schema, but it can be blank. If we want to allow people to omit the connections field in YAML we can generate a {} schema in the conns file

2022-08-11 22:21 UTC, coryodaniel commented on pkg/bundle/templates/terraform/massdriver.yaml
>  connections:
We always need a connection schema, but it can be blank. If we want to allow people to omit the connections field in YAML we can generate a {} schema in the conns file

2022-08-11 23:42 UTC, WillBeebe commented
I'm working on the no-connections default for templates but otherwise ready for review!

2022-08-12 03:32 UTC, coryodaniel commented
I’m going to look in AM!

Cory ODaniel
Mobile: 310.606.0257
***@***.***
medium: @coryodaniel ***@***.***>
twitter: @coryodaniel <https://twitter.com/coryodaniel>

On Thu, Aug 11 2022 at 4:42 PM, Will Beebe ***@***.***>
wrote:

> I'm working on the no-connections default for templates but otherwise
> ready for review!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/massdriver-cloud/massdriver-cli/pull/87#issuecomment-1212595409>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAC2Q52KTNBDRMGX344A6DVYWFVXANCNFSM56GVOC7Q>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-08-12 04:21 UTC, WillBeebe commented
Sounds good! I had a little revelation and app package is much simpler now.

2022-08-12 04:33 UTC, WillBeebe commented on cmd/bundle.go
> +	Use:   "new",
calling out adding `mass bundle new`, it does the same as `generate`

2022-08-12 04:35 UTC, WillBeebe commented on pkg/application/types.go
> -	Deployment   Deployment              `json:"deployment" yaml:"deployment"`
yanked

- Deployment
- Dependencies

added

- Connections
- Artifacts
- App

2022-08-12 06:33 UTC, xpositivityx reviewed
overall there are some really great refactors in here!

2022-08-12 06:33 UTC, xpositivityx commented on cmd/bundle.go
> +	b, err := bundle.Parse(common.MassdriverYamlFilename, nil)
I feel like this same chain of events happens with a couple different functions. I wonder if it would be worth adding checkIsBundle and checkIsApplication to the bundle and app types and just dependency injecting that in to a more general version of this code.

2022-08-12 15:21 UTC, coryodaniel requested changes
![issa bundle](https://imgflip.com/i/6pqn68)

A few notes, consider approved after addressing.

2022-08-12 15:21 UTC, coryodaniel commented on pkg/application/types.go
> -	Deployment   Deployment              `json:"deployment" yaml:"deployment"`
Nice artifacts will be blank here for a while, I'm pretty sure publish requires them, so it can be an empty map if not present in the yaml file.

2022-08-12 15:21 UTC, coryodaniel commented on pkg/application/types.go
> +	Policies []string          `json:"policies" yaml:"policies"`
I think policies should be an array, but tell me if there is any value in them being a map ... with the way we process them in `for_each` in tf across all the clouds its just iterating on the array. Not sure if there is any value to having a named reference to them. Probably not. :bike: :shed:

2022-08-12 15:21 UTC, coryodaniel commented on pkg/application/types.go
> +func (app *Application) AsBundle() *bundle.Bundle {
noice.

2022-08-12 15:21 UTC, coryodaniel commented on pkg/bundle/hydrate.go
> +	if b.Connections == nil {
We might need to do the same for Artifacts, id double check a yaml w/o an `artifacts` key.

For context, charts like Timescale and Clickhouse will have artifacts, but end user apps _probably_ wont until we release the web/api service artdef. We need to generalize there a bit, so I could easily see a fair amount of apps (including the massdriver platform-api app) having no `artifacts` set in the YAML file.

2022-08-12 15:21 UTC, coryodaniel commented on pkg/bundle/prompt.go
> +func GetConnections(t *template.Data) error {
If we dont have an artficat definitions list function now on the REST API, when we expose `deploy` function from the graph next week _all_ functions will be exposed, so we'll be able to make a graph call from here to get that list.

2022-08-12 15:21 UTC, coryodaniel commented on pkg/bundle/prompt.go
> +	artifacts, err := common.GetMassdriverArtifacts()
We should be careful to refer to them as artifact definitions or definitions since they aren't an artifact yet. Once the graph is exposed, i could see value in `mass artifact get ecomm-prod-cluster-0000 --field k8s_authentication --format kubeconfig | raw > ~/.kubeconfig` and it would be nice for the go code not to be overloading the word "artifact"

2022-08-12 15:21 UTC, coryodaniel commented on pkg/bundle/prompt.go
> +		Message: "What artifacts does your application depend on? If you have no dependencies just hit enter or only select (None)",
If we are including this prompt on bundles now, `application` might be confusing here. Can we word the sentence without `app` or `bundle` or possible take in the `type` and interpolate?

2022-08-12 15:21 UTC, coryodaniel commented on pkg/bundle/prompt.go
> +		log.Info().Msgf("Please enter a name for the dependency %v", v)
I never know the right level of information to present, we might be able to clarify this in the docs (and hopefully they've read those if they are making a bundle|app), but should we say something like the following or is it too wordy.

`Please enter a name for the dependency. This will be the variable name used to reference it in your app|bundle IaC`

2022-08-12 15:21 UTC, coryodaniel commented on pkg/bundle/prompt.go
> +		depMap[result] = fmt.Sprintf("massdriver/%s", selectedDeps[i])
When we pull this from the api we'll need to remove `massdriver/` from it as it will have prefixes on it already, including private bundles like `evilcorp/iis-server-4`

2022-08-12 15:21 UTC, coryodaniel commented on pkg/bundle/templates/terraform/massdriver.yaml
> +  required: ["*"]
'*' doesnt https://www.jsonschemavalidator.net/s/BnUUyUot, i used this as short hand the other day, sorry. I wish :D

We'll need to https://shopify.github.io/liquid/filters/join/ `.Connections`

2022-08-12 15:21 UTC, coryodaniel commented on pkg/common/artifacts.go
> +package common
leet

2022-08-12 15:21 UTC, coryodaniel commented on pkg/common/constants.go
> +var FileIgnores []string = []string{
Definitely not something for now, but we should add a backlog item to make a `.massignore`. We'll probably want to exclude these forever in the cli, but devs may want to exclude other files in the directory.

2022-08-12 18:29 UTC, WillBeebe commented on pkg/bundle/templates/terraform/massdriver.yaml
> +  required: ["*"]
Lol I see... Fixed :)

2022-08-12 18:33 UTC, WillBeebe commented on pkg/common/constants.go
> +var FileIgnores []string = []string{
Ticket created.

2022-08-12 18:34 UTC, WillBeebe commented on pkg/bundle/prompt.go
> +func GetConnections(t *template.Data) error {
Oh dopeee, that's going to be another game-changer.

2022-08-12 18:49 UTC, WillBeebe commented on pkg/bundle/prompt.go
> +		Message: "What artifacts does your application depend on? If you have no dependencies just hit enter or only select (None)",
Good point, thank you

2022-08-12 18:59 UTC, WillBeebe commented on pkg/bundle/prompt.go
> +	artifacts, err := common.GetMassdriverArtifacts()
Good point, I remember we talked about artifact / artifact-definition / etc.. Thanks always for the reminder, I'll update this to be accurate

2022-08-12 19:10 UTC, WillBeebe commented on pkg/application/types.go
> +	Policies []string          `json:"policies" yaml:"policies"`
Good q. We've migrated some arrays to maps in TF to avoid the whole "recreates resources when the index in the array changes". However, we don't use policies _directly_. We use the policies to grab values from the `security` block and build a map of policy + iam. Since we for_each that map to create TF resources, I think we're good leaving Policies as an array in the CLI.

2022-08-12 19:46 UTC, WillBeebe commented on cmd/bundle.go
> +	b, err := bundle.Parse(common.MassdriverYamlFilename, nil)
Created a ticket to come back to this, will be a good addition.

2022-08-12 19:58 UTC, WillBeebe commented
> ![issa bundle]
> 
> A few notes, consider approved after addressing.

@coryodaniel feedback addressed

2022-08-12 23:14 UTC, coryodaniel approved these changes

2022-08-13 02:43 UTC, merged